### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Shikopat** [Ja7ad/ShadowRocket#3]
here's list of phishing, trackers, ads for IR region:
https://pastebin.com/raw/jmBL8w2b
please add them in your config

Here's updated IP list for Telegram:
https://pastebin.com/raw/eMxVNaJA

Here's Updated list of IR websites for direct:
https://github.com/SamadiPour/iran-hosted-domains/releases/download/202108130905/shadowrocket.conf

**Comment by ja7ad** [comment]
Thanks  updated to version 0.3.0
