### ISSUE TITLE
https://esale.ikco.ir

### ISSUE THREAD

**Issue by Amirjafarnezhad** [Ja7ad/ShadowRocket#5]
این سایت رو هم نمیتونه باز کنه

**Comment by ja7ad** [comment]
No problem

![image](https://user-images.githubusercontent.com/56496801/143533167-ecdf0bf2-c0cc-4cf4-ab5a-e1dc8ed416f9.png)

![image](https://user-images.githubusercontent.com/56496801/143533181-6ede88e2-e70d-405d-ad1a-24fe6a418fbb.png)
