### ISSUE TITLE
Whats app problem

### ISSUE THREAD

**Issue by AbasJalali** [Ja7ad/ShadowRocket#7]
Hi thank you for your good job
But with last config whats app not working please fix that
Regards

**Comment by ja7ad** [comment]
> Hi thank you for your good job But with last config whats app not working please fix that Regards

Hello

whatsapp has been updated and add new rules, please update [shadowIR.conf](https://github.com/Ja7ad/ShadowRocket/blob/main/shadowIR.conf) file in your shadowrocket.

https://github.com/Ja7ad/ShadowRocket/commit/77aec0d676459ecc86885ec46387b553fa5a4c26

**Comment by musa-42** [comment]
مشکل هنوز حل نشده 
![IMG_1266](https://github.com/Ja7ad/ShadowRocket/assets/83463048/556291a6-c83d-4509-989e-9ca98ca4f417)

**Comment by Airuop** [comment]
> مشکل هنوز حل نشده 

هرموقع با برنامه یا سایتی مشکل داشتی اول لاگ بگیر اگر دایرکت بود ادد تو رول بزن بعدش بزار رو پروکسی سیو کن 
این کار باعث میشه کانفیگ رو دوره ای  آپدیت کنی
